// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcrnfjdzkelrlpkfjacs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjcm5mamR6a2Vscmxwa2ZqYWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDI1MzgsImV4cCI6MjA2ODMxODUzOH0.5R5EhHbvKYCEs-3bpOyQgTO_EeR8rfkWk81oTMVIZmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});